apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: python-app
          image: gcr.io/omar-mohamed-el-sayed-project/omarpython
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: my-app-cm1
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000